tryber/sd-09-project-frontend-online-store

README.md, src/services/api.js
=>  [GROUP 8] Implementacao api mercado livre

package-lock.json, src/App.js
=> [GROUP 8] Requisito 2

src/App.js, src/services/api.js
=> [GRUPO-11][FEAT] - RequestAPI

src/App.js, src/components/HomePage.jsx, src/components/SearchBar.jsx
=> [GRUPO 11] [FEAT] - Search Bar

package-lock.json, src/App.js, src/components/index.js, src/pages/AnotherPageComponent.js, src/pages/ProductList.js, src/pages/index.js
=> added requirement 2

src/App.js, src/services/api.js
=> Requisito 1

package-lock.json, src/services/api.js
=> [FEAT 1] Fetch Api

src/services/api.js
=> Adiciona requisito 1

src/App.js, src/components/searchBar.jsx
=> [FEAT 2] Search Bar

src/services/api.js
=> [Grupo 04] -  Módulo de Acesso a API

package-lock.json, package.json, src/App.js, src/Components/categoriesCheckBox.jsx, src/Components/categoriesList.jsx, src/Components/emptyCart.jsx, src/Components/homePage.jsx, src/Components/input.jsx, src/services/api.js
=> implemented asideBar CategoriesList

src/App.js, src/services/api.js
=> Implemented api.js function

src/App.js, src/Components/input.jsx, src/services/api.js
=> implemented homeInput to app

package-lock.json, package.json, src/App.js, src/Components/emptyCart.jsx, src/Components/homePage.jsx, src/Components/input.jsx, src/services/api.js
=> implemented emptyCart component

package-lock.json, src/services/api.js
=> [GRUPO 28] - REQUISITO 1

package-lock.json, src/App.js, src/pages/ProductList.js
Criada a Route para ProductList em App.js. Criada pasta src/pages
para componentes de páginas. Criado componente ProductList.
=> [feat] [req 2] Página Inicial

src/App.js, src/components/ProductList.js
=> [GRUPO 28]  - Requisito 2

package-lock.json, src/App.js, src/services/api.js
=> [group-14][Req.01: implement api.js functions]

src/App.js, src/components/MainPage.js
Agora sim, pull request na branch correta 🚀
=> Group 21 - Adiciona requisito 2

src/services/api.js
requisito 1 feito, 2 commit cada um para um dos exercícios propostos no requisito.
=> [Grupo 29] requisito 1

src/App.js, src/components/CartButton.jsx, src/components/ShoppingCart.jsx, src/components/searchBar.jsx
=> [FEAT] ShoppingCart / CartButton

src/App.js, src/services/api.js
=> [Group 1] Feat 1

src/App.js, src/services/api.js
=> [Grupo 10][First Requeriment]

.github/workflows/main.yml, src/App.js, src/components/Home.js, src/components/ProductList.js, src/services/api.js
=> [GRUPO6][REQUISITO2] Crie uma página de listagem de produtos vazia

src/App.js, src/components/ProductList.jsx
=> [GRUPO 29] Requisito 2

src/App.js, src/components/filterCategories.jsx
=> [FEAT] Category-List

src/components/Categories.js, src/components/MainPage.js
=> group-21 - Adiciona requisito 4

src/App.js, src/services/api.js
=> [Feat][Requisito 1 acesso a API]

src/App.js, src/pages/Cart.js
Exercício 3: 
- criar um link para a pagina de carinho de compras
- criar a pagina de carrinho de compras vazio
=> [Grupo 23][No Master Store] - Exercício 3

src/App.js, src/components/ProductsList.js, src/pages/Home.js
=> [GROUP 8] Requisito 5 - liste produtos

package-lock.json, src/App.js, src/components/ProductsShowcase.js
Cria uma pasta components para armazenagem de todos os components que serão criados durante o projeto, renderiza na pagina inicial do app um input e uma mensagem como pede o requisito 2.
=> Requisito 2

src/App.js, src/services/api.js
=> Implementar rotas

src/App.js, src/components/ProductList.jsx, src/components/ShoppingCart.jsx
=> [GRUPO 29] Requisito 03

src/components/Product.js, src/components/SearchBar.js
Nova Feature - Requisito 05 - Listagem de produtos
=> [Grupo 4] - Feat/Listagem de produtos

src/App.js, src/Home.js, src/ProductCard.js, src/ProductList.js
=> Requisito 5

src/components/CardItem.js, src/components/MainPage.js
Requisito 5 feito em grupo :rocket:
=> Group 21 - Adiciona requisito 5

src/App.js, src/components/ProductList.jsx, src/components/ShoppingCart.jsx
=> [Group-14][Group 14/feat/03]

src/Home.js
Unificando todos os requisitos de 1 a 5 prontos.
=> Main group 22 feats1 5

src/App.js, src/pages/ProductList.js, src/pages/ShoppingCart.js
=> [FEAT][REQUIREMENT 03][SHOPPING CART BUTTON]

src/components/CategoriesList.js, src/components/SearchBar.js
Feature do requisito 06. Que se trata de filtrar os produtor a partir do clique nas categorias listadas.
=> [Grupo 04] - Feat / Requisito-06

src/App.js, src/components/Home.jsx, src/components/ShoppingCart.jsx
=> [GRUPO 1] Main group 1 ft 3

src/components/Home.jsx, src/components/ListCategories.jsx, src/components/ProductList.jsx, src/components/RenderElements.jsx
=> Main Group 31 - Merge requirement 4 and 5

src/App.css, src/App.js, src/ProductList.js
=> [GROUP 5][FEAT][LIST PRODUCTS]

package-lock.json, package.json, src/services/api.js
=> [GROUP 5][FEATURE] - Fetch API functions

src/App.js, src/components/Product.js, src/components/SearchBar.js, src/components/ShoppingCart.js, src/components/ShoppingCartButton.js, src/index.js, src/pages/Datails.js, src/pages/Details.js
Feature -  Página de detalhes do produto clicado.
=> [Grupo 04] - Feat/Requisito07

package-lock.json, src/services/api.js
=> [Grupo 30] - Acessando Api

src/App.js, src/components/Cart.js, src/components/ProductList.js
=> [GRUPO6][REQUISITO3] Crie a página do carrinho de compras

src/App.js, src/pages/home.js
Criação do diretório pages dentro do diretório src para a criação do componente home.
=> [Grupo 20] Requisito 2 para análise

src/App.js, src/components/CardItem.js, src/components/ItemDetails.js, src/components/MainPage.js, src/services/api.js
=> Group 21/feat/req 7

src/App.js, src/components/ProductsList.js, src/pages/Home.js, src/pages/ProductDetails.js
=> [Group 8] - equisito 7, talvez precise do 6?

src/components/ProductList.js
=> [GRUPO6][REQUISITO4] Liste as categorias de produtos disponíveis via API na página principal

src/App.js, src/components/Card.js, src/pages/LandingPage.js
=> Main group 23 feat/requisito5

src/App.js, src/components/CardItem.js, src/components/ItemCart.js, src/components/MainPage.js, src/components/ShoppingCart.js
PRIORIDADE 3 - Na tela de listagem de produtos, permitir adicionar o produto ao carrinho.
Observações técnicas
Configure uma forma de adicionar produtos ao carrinho de compras a partir da tela de listagem de produtos.
O que será verificado:
- Adiciona da tela de listagem um produto que aparece no carrinho
=> Group 21 - Adiciona requisito 8

src/components/RatingForm.js, src/pages/ProductDetails.js
=> [GROUP 8] Requerimento 11 - colocando um forms para rating

src/components/ProductList.js
=> [GRUPO6][REQUISITO5] Criar a listagem de produtos

src/App.js, src/components/ItemDetails.js
Desenvolvido requisito 9 em time!
=> Group 21 - Adiciona requisito 9

src/pages/CardProduct.jsx, src/pages/ProductList.js, src/services/api.js
=> [FEAT]REQUIREMENT5][HOME]

src/components/ItemCart.js
Implementado requisito 10 em grupo!
=> Group 21 - Adiciona requisito 10

src/pages/Home.js, src/shoppingCart.js
=> [GROUP 8] Requisito 8 adiciona carrinho

src/App.js, src/components/ItemCard.jsx, src/components/SearchBar.jsx, src/pages/ItemDetails.js
=> [FEAT] Grupo 12 - Implementada a pagina de detalhes do produto.

src/components/Categories.jsx
Pessoal, fiz a alteração da listagem de categorias para radio buttons.
Fiz os testes dos requisitos e estão todos do 1 ao 5 passando.
=> Troca button para radioButton na lista de categorias

package-lock.json, src/App.js, src/components/Carrinho.js, src/components/Categories.jsx, src/components/Home.js, src/components/SearchCard.jsx, src/index.css
Feitas implementações das _features_ 4, 5 e 6. Requisitando code-review.
=> [FEAT] [4, 5, 6]

src/pages/ProductDetails.js
Usei a implementação do Johne no requisito 8 pra resolver essa
=> g13-requisito 9

.github/workflows/main.yml, README.md, src/App.js, src/components/InitialPage.js, src/components/ListOfCategories.js, src/services/api.js
Pessoal,
Criei o componente ListOfCategories que é responsável por renderizar uma lista com os nomes de todas as categorias, que são passados por props.
Na Initial page, acrescentei um estado para receber as categorias vindas da API e armazená-las. Depois disso, já que se trata de um array, faço um map para criar uma li com cada nome.
=> [Requisito 4]

src/components/Home.jsx, src/components/ListOfCategories.jsx, src/components/SearchBar.jsx
=> [GRUPO 1] Feature 6

src/pages/Home.js, src/pages/ProductDetails.js, src/shoppingCart.js
=> [GROUP 8] - Requisito 9 - adiciona items ao carrinho a partir da pagina de detalhes

src/components/AddToCartButton.js, src/components/Product.js, src/components/ProductCart.js, src/components/SearchBar.js, src/components/ShoppingCart.js, src/pages/Details.js
Feature de mostrar a lista de produtos no carrinho
=> [Grupo 04] - Feat / Requisito 10

src/App.js, src/components/CartButton.js, src/components/ProductList.js
=> [Grupo 28] - Requisito 3 

src/App.js, src/Categorias.js, src/Home.js, src/ProductCard.js, src/ProductList.js, src/ShoppingCart.js
=> Requisito 8

src/App.css, src/components/ProductItem.jsx, src/components/ProductList.js, src/services/api.js
**Atenção: Falta alterar o parâmetro de categoria na linha 25 do ProductList**
=> [Grupo 28] - Requisito 5

src/App.js, src/Categorias.js, src/Home.js, src/ProductCard.js, src/ProductDetails.js, src/ProductList.js, src/ShoppingCart.js
=> Requisito 9

src/App.js, src/Categorias.js, src/Home.js, src/ProductCard.js, src/ProductDetails.js, src/ProductList.js, src/ShoppingCart.js
=> Requisito 10

src/Components/cart.jsx, src/Components/details.jsx, src/services/dataCart.js
=> Main group 15 fix issues

src/pages/Home.js, src/pages/ProductDetails.js, src/shoppingCart.js
=> [GROUP 8] - Requisito 10

src/App.js, src/components/CardItem.js, src/components/ItemCart.js, src/components/ItemDetails.js, src/components/MainPage.js, src/components/ShoppingCart.js
Desenvolvido o requisito 13 em grupo.
=> Group 21 - Adiciona requisito 13

src/App.js, src/Components/CardShoppingCart/CardShoppingCart.css, src/Components/CardShoppingCart/CardShoppingCart.js, src/Components/CheckoutForm/CheckoutForm.css, src/Components/CheckoutForm/CheckoutForm.js, src/Components/ProductCard/ProductCard.js, src/pages/Checkout.js, src/pages/Home.js, src/pages/ShoppingCart.js
A página ainda não tá completamente pronta, faltam adicionar alguns componentes pra ficar completa, mas por já estar passando no requisito, já criei o PR
=> g13 requisito 12

src/components/CardItem.js
Desenvolvido requisito 21 em grupo.
=> Group 21 - Adiciona requisito 15

src/App.js, src/Components/Card.js, src/Pages/Search.jsx, src/Pages/SingleView.jsx
=> [Grupo 10][Requerimento 07]

src/App.js, src/components/ProductCard.jsx, src/components/ProductDetails.jsx, src/components/ProductList.jsx, src/services/api.js
=> [GRUPO 29] requisito 07

src/pages/ProductDetais.js
…de exibição detalhada. :white_check_mark:
=> [No Master No Store] feat ex 9 add itens no carrinho

package-lock.json, src/Components/cart.jsx, src/Components/cartItem.jsx
a lógica está funcionando, só tem algum erro relacionado ao react que não estou identificando.
Os botões funcionam, mas depois de alguns clicks quebra e começa a deletar os itens do carrinho :man_shrugging:
=> praticamente pronto, soh mais alguns ajustes amanha

src/App.js, src/components/CategoryList/index.js, src/components/Product/Product.jsx, src/components/Product/index.js, src/pages/HomePage/HomePage.jsx, src/pages/ProductDetails/ProductDetails.jsx, src/pages/ProductDetails/index.js, src/pages/ProductsPage/ProductsPage.jsx, src/pages/ProductsPage/index.js
=> [ GRUPO 11 ][ FEAT ] Redirecione para uma tela com a exibição detalhada ao clicar na exibição resumida de um produto

src/components/EvaluatorForm.js, src/components/Product.js, src/components/ProductCart.js, src/components/SearchBar.js, src/components/ShoppingCart.js, src/pages/Details.js
Feature Requisito 14 - Limitar a quantidade de produtos adicionados no carrinho, pela quantidade de produtos no estoque.
=> [Grupo 04] Feat - Requisito 14

src/components/Product.js, src/pages/Details.js
Feature - Mostar quais produtor tem o frete grátis. :D
=> [Grupo 04] - Feat/ Requisito 15

src/App.js, src/components/ProductCard.jsx, src/components/ProductDetails.jsx
=> [GRUPO 1] FEATURE 7

src/App.js, src/pages/Checkout.js, src/pages/Home.js, src/pages/ProductDetails.js, src/shoppingCart.js
=> [GROUP 8] - Requisito 12

src/App.js, src/components/CartIcon.jsx, src/components/CategoriesList.js, src/components/CategoryInput.js, src/components/NoSearchText.js, src/components/SearchStatusMsg.js, src/pages/ProductList.js
* Implementa método selectCategory em ProductList;
* Update CategoriesList & CategoryInput for callbacks;
* Adiciona selectCategory e statusMessage ao estado de ProductList;
* Renomeia e muda aplicação de NoSearchText para SearchStatusMsg;
* Declara condicional noSearchResults em ProductList para melhor
legibilidade.
=> Group 35 - feat(ProductList): Adiciona requisito 6

src/App.js, src/components/CategoriesList.css, src/components/ProductCard.css, src/components/ProductCard.js, src/components/ProductDetails.css, src/components/ProductDetails.js, src/components/SearchResults.css, src/components/SearchResults.js
PRIORIDADE 3 - Como pessoa usuária, eu quero clicar no card do produto e visualizar a exibição detalhada do produto com nome do produto, imagem, preço e especificação técnica. A tela também deve possuir um botão que leve ao carrinho de compras.
=> [ GRUPO 35 ] Requisito 07

src/App.js, src/Components/cart.jsx, src/Components/checkout.jsx, src/Components/forms.jsx, src/Components/homePage.jsx, src/Components/paymentMethod.jsx, src/Components/reviewCart.jsx
=> Main group 15 requisito 12

src/components/Home.jsx, src/components/ProductCard.jsx, src/components/ShoppingCart.jsx
=> [GRUPO 1] Requisito 8

src/components/Product.js, src/components/Products.js
=> [grupo 19] mergeando req7 e req8

src/components/ProductDetails.jsx, src/components/ShoppingCart.jsx
=> [GRUPO 1] - Feature 9

src/components/AddToCart.jsx, src/components/ProductsEvaluation.jsx, src/components/ShoppingCart.jsx, src/pages/ItemDetails.js
=> [FEAT] ProductsEvaluation

src/App.js, src/components/Forms.jsx, src/components/PaymentMethod.jsx, src/components/ReviewCart.jsx, src/components/ShoppingCart.jsx, src/pages/Checkout.js
Requisito 12 com uma falha de lint.
=> [FEAT] Checkout

src/components/Product.js, src/components/ProductDetails.js, src/components/Products.js, src/pages/Details.js
=> Added Req9

src/pages/Home.js, src/pages/ProductDetails.js, src/shoppingCart.js
=> [GROUP 8] - Requisito 13

src/components/RatingForm.js, src/services/api.js
Criação do componente para avaliação.
=> Requisito 11, Grupo 34

src/__tests__/requirement09.test.js, src/services/Home.js, src/services/ProductCard.js, src/services/ProductDetails.js, src/services/ProductsList.js, src/services/ShoppingCart.js, src/services/ShoppingCartBtn.js, src/services/functions.js
=> requirements 8 e 9 com localstorage

src/App.js, src/components/Product/Product.jsx, src/pages/HomePage/HomePage.jsx, src/pages/ProductDetails/ProductDetails.jsx
=> [GRUPO 11][FEAT] Adicione um produto ao carrinho a partir de sua tela de exibição detalhada

src/components/ProductDetails.jsx, src/components/RatingForm.jsx
=>  [GRUPO 1] FEATURE 11

src/App.js, src/components/ProductCard.js, src/pages/ProductDetails.js, src/services/api.js
=> [FEAT][REQUIREMENT 07][PRODUCT DETAILS PAGE]

src/components/Product.js, src/pages/ShoppingCart.js
=> adicionado requisito 10

src/App.js, src/components/Carrinho.js, src/components/ItemsCart.jsx
Vem ni noix 80% \o/
Bora de aprovação no projeto!! 
#vqv
#rumoAo100/100
#valeuGalera 🚀
=> Requisito 10 | Adicionados botoes no carrinho (aumenta, diminui quantidade e remove produto)

src/App.js, src/components/CardReview.js, src/components/ClientsData.js, src/components/PayMethod.js, src/components/ReviewProducts.js, src/components/styles/style.css, src/pages/Cart.js, src/pages/Checkout.js, src/pages/LandingPage.js, src/pages/ListCategories.js, src/pages/ProductDetais.js
PRIORIDADE 4 - Implementar tela para a finalização da compra. A tela deve conter uma seção para revisão dos produtos com o valor total da compra, um formulário para ter as informações do comprador e um a seção para escolher o método de pagamento. Ao se clicar em "Comprar", deve-se validar que o formulário está preenchido e que a forma de pagamento foi escolhida e, em caso positivo, deve-se zerar o estado, redirecionar para a tela inicial (listagem de produtos). Caso algo não tenha sido preenchido, mantém-se na mesma tela com o dados sem apagar e destaca-se os campos não preenchidos em vermelho.
**Observações técnicas**
>O último grande passo do fluxo do e-commerce é a finalização da compra por parte de quem usa.
- Adicione um botão para finalizar a compra. Este botão ao ser clicado, deve …
=> [No Master, No Store] Requisito 12 - Finalizar compra com resumo, dados e pagamento

src/components/CartProduct/CartProduct.jsx, src/components/IncrementDecrementButton/IncrementDecrementButton.jsx, src/components/IncrementDecrementButton/index.js
=> [GRUPO-11][FEAT] Adiciona produtos ao carrinho e manipula suas quantidades

README.md, src/App.js, src/components/Home.jsx, src/components/ProductCard.jsx, src/components/ProductDetails.jsx, src/components/RatingForm.jsx, src/components/ShoppingCart.jsx
=> [GRUPO 1] Feature 10

package-lock.json, package.json, src/App.js, src/components/CartProduct/CartProduct.jsx, src/components/Header/Header.jsx, src/components/InputContext/InputContext.jsx
- [  ]  Vê a quantidade de produtos no carrinho da tela de listagem
- [  ] Vê a quantidade de produtos no carrinho da tela de detalhes
=> [GRUPO-11][FEAT] Vê a quantidade de produtos no carrinho

src/App.css, src/App.js, src/components/RatingForm.css, src/components/RatingForm.js, src/pages/Checkout.css, src/pages/Checkout.js, src/pages/Home.css, src/pages/Home.js, src/pages/ProductDetails.css, src/pages/ProductDetails.js, src/shoppingCart.css, src/shoppingCart.js
=> [GROUP 8] - Requisitos bônus

src/components/Category.jsx, src/pages/Home.jsx
=> [grupo36][prioridade 2]

src/components/Category.jsx, src/pages/DetailedProduct.jsx, src/pages/Home.jsx
=> [Grupo 36][Prioridade 2]

src/components/ReviewCart.jsx
Implementado o cálculo do total do carrinho na pagina de fialização de compra utilizando os objetos guardados no local storage.
=> [FIX] Implementado o total do carrinho de compras

src/App.css, src/App.js, src/components/ProductDetails.js, src/components/ProductItem.js, src/components/ProductList.js
=> [Grupo 28] - Requisito 07

src/components/CategoriesList.js, src/components/ProductCard.js, src/components/SearchBar.js, src/pages/ProductList.js
Divisão de partes do código em componentes para maior clareza e organização
=> [REFACTOR][COMPONENTS][Refatora partes de ProductList em componentes]

src/App.js, src/components/Home.jsx, src/components/OrderSummary.jsx, src/components/ProductCard.jsx, src/components/ProductDetails.jsx, src/components/ShoppingCart.jsx
=> [GRUPO 1] Feature 12

src/components/ShoppingCart.jsx
=> [FEAT]Implementada a feature que limita o carrinho ate a quantidade disponivel do produto.

src/components/ProductCard.js, src/components/shopping_cart/CartItem.js, src/components/shopping_cart/ShoppingCart.js
=> [GROUP 5] - Requisito 8

src/App.js, src/components/CheckoutCart.jsx, src/components/ProductDetails.jsx, src/components/ShoppingCart.jsx, src/components/ShoppingCartItem.jsx
Adicionei uma lógica para atualizar a chave quantity do array ProductAtCart no arquivo data.js, essa lógica está contida no componente ShoppingCartItem nas funções de soma e subtração da quantidade de produtos, e fiz a criação do componente checkout para finalização da compra. o componente está passando nos testes mas não está "completo" em relação ao layout de exemplo fornecido no read.me
=> [GRUPO 29] requisito 12

src/components/ProductDetailed.js
=> [GROUP 5] REQUISITO 9

package-lock.json, src/components/ProductCard.jsx, src/components/ProductList.jsx, src/components/ShoppingCartItem.jsx, src/services/dataservices.js
Requisito 14 ok. 
Acrescentei na função de sumQuantity uma ordem de negócio que permite acrescentar valor apenas quando o valor for menor que a quantidade total disponível em estoque. (Estoque verificado por API)
=> [Grupo 29] requisito 14

src/components/FreeShipping/FreeShipping.jsx, src/components/FreeShipping/index.js, src/components/Product/Product.jsx, src/pages/ProductDetails/ProductDetails.jsx
=> [ GRUPO 11 ][ FEAT ] Mostre quais produtos tem o frete grátis

src/pages/Cart.js, src/pages/Home.js, src/pages/ProductDetails.js, src/styles/Cart.css
=> requirement 10

src/App.js, src/components/Button/Button.jsx, src/components/CartProduct/CartProduct.jsx, src/components/IncrementDecrementButton/IncrementDecrementButton.jsx, src/components/Product/Product.jsx, src/components/ProductDescription/ProductDescription.jsx, src/components/ProductDescription/index.js, src/components/ReviewsSection/ReviewsSection.jsx, src/components/ReviewsSection/index.js, src/pages/CartPage/CartPage.jsx, src/pages/ProductDetails/ProductDetails.jsx
=> [ GRUPO 11 ][ FEAT ] Manipulação de quantidades

src/ProductDetail.js, src/Products.js
including free-shipping information on products and product Details
=> [ Grupo 30] Requisito 15

src/App.js, src/components/Home.jsx, src/components/OrderSummary.jsx, src/components/ProductCard.jsx, src/components/ProductDetails.jsx
=> [GRUPO 1] Feature 13

src/App.js, src/components/CartItem.js, src/components/ProductCard.js, src/components/ProductDetails.js, src/pages/ShoppingCart.js, src/styles/components/CartItem.css, src/styles/components/ProductCard.css, src/styles/pages/ShoppingCart.css
obs.: Refatorada a função que adiciona o produto no carrinho.
=> [Group-20][Req-10]

README.md, package-lock.json, src/App.css, src/App.js, src/components/Cart.jsx, src/components/CartItem.jsx, src/components/Categories.jsx, src/components/ProductCard.jsx, src/components/ProductDetail.jsx, src/components/ProductList.jsx, src/components/SearchProduct.jsx, src/css/productList.css, src/services/api.js
**[BUG]** - quando decrementamos o item até 0, que clicamos novamente ele incrementa e volta a 0.
**[SOLUÇÃO]** - sugerir 'remover item do carrinho' ao chegar em 0.
=> Main group 3 Requisito 10

src/App.css, src/components/ProductItem.jsx, src/components/ProductList.js, src/components/ShoppingCartItens.jsx, src/pages/InitialPage.js, src/pages/ShoppingCart.js
ajuste referente ao conflito na branch do requisito 08
=> ajuste referente ao conflito na branch do requisito 08

src/App.js, src/components/AbstractCartHandler.js, src/components/AddToCartButton.js, src/components/CartIcon.jsx, src/components/SearchResults.js, src/pages/CartShop.jsx, src/pages/ProductDetails.js, src/pages/ProductList.js, src/services/cart.js, src/services/objects.js
* Implementa exibição da quantidade de items em CartIcon;
* Transfere gerenciamento do cart para App.js;
* Refatora aplicações de cart nos componentes;
* Corrige/implementa proptypes.
=> Group 35 - feat(CartIcon): Adiciona requisito 13

src/App.js, src/components/AbstractCartHandler.js, src/components/AddToCartButton.js, src/components/CartIcon.jsx, src/components/ProductCard.js, src/components/SearchResults.js, src/pages/CartShop.jsx, src/pages/ProductDetails.js, src/pages/ProductList.js, src/services/cart.js, src/services/objects.js
* (services/objects) Altera reshapeObjects para selecionar propriedade do frete;
* (ProductCard) Adiciona renderização condicional para exibir 'Frete Grátis';
=> Group 35 - feat(ProductCard): Adiciona requisito 15

src/App.css, src/components/ProductDetails.js
os comentários estão sendo salvos e renderizados na pagina de detalhes. Só está faltando modificar a forma de salvar e puxar do localStorage para que os comentários sejam para cada produto clicado.
=> [Grupo 28] - Requisito 11

src/App.js, src/Cart.js, src/CartQuantity.js, src/CheckOut.js, src/ItemCart.js, src/ProductDetail.js, src/Products.js
Trying to do the purchase limit by inventory.
=> [Grupo 30] task14

src/App.js, src/components/Category.jsx, src/components/Product.jsx, src/components/ProductCart.jsx, src/pages/Cart.jsx, src/pages/DetailedProduct.jsx, src/pages/Home.jsx, src/services/api.js, src/services/functions.js
[]- Requisito 7
[]- Requisito 8
[]- Requisito 9
=> Prioridade 3

package-lock.json
=> cria componente jesus

src/components/ButtonAdd.jsx, src/components/ProductItem.jsx, src/components/ProductList.js, src/pages/ProductDetails.js
- Criado botão para adicionar produto no carrinho na page de detalhes,
- Criado  novo componente 'ButtonAdd' para ser utilizado mesmo componente tanto na lista de produtos quanto na página de detalhes.
=> realizado requisito 09

src/pages/CartPage.jsx
Modifica funcao de adicionar e remover itens em CartPage.jsx
=> Main group 17 feat/ivan

src/components/Checkout.jsx, src/components/Detalhes.jsx, src/components/ItemsCart.jsx, src/components/SearchCard.jsx
Fim do projeto básico
Partiu estilizar a página
#vqv
=> Main group 24 feat 14 15

src/components/ItemCard.jsx
=> [FEAT] Free Shipping Info

src/App.css, src/App.js, src/components/Category.jsx, src/components/Product.jsx, src/components/ProductCart.jsx, src/components/ProductCheckout.jsx, src/components/ProductDetail.jsx, src/components/ProductEvaluation.jsx, src/components/Shipping.jsx, src/pages/Cart.css, src/pages/Cart.jsx, src/pages/Checkout.css, src/pages/Checkout.jsx, src/pages/DetailedProduct.css, src/pages/DetailedProduct.jsx, src/pages/Home.css, src/pages/Home.jsx, src/pages/NotFound.jsx, src/pages/home.css, src/services/functions.js
=> [G36][Bônus]

src/App.js, src/components/CartIcon.js, src/components/CartItem.js, src/components/ProductCard.js, src/components/ProductDetails.js, src/components/RatingEvaluation.js, src/components/SearchBar.js, src/pages/Home.js, src/pages/ShoppingCart.js, src/styles/components/CartIcon.css, src/styles/components/ProductCard.css, src/styles/components/ProductDetails.css, src/styles/components/SearchBar.css
=> [Group-20][Req-Bonus]
